# Generated by Django 4.2.5 on 2023-10-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartRoom', '0002_name_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='password',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
