# Generated by Django 4.2.5 on 2023-10-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartRoom', '0003_name_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
