# Generated by Django 4.2.5 on 2023-10-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartRoom', '0004_room_delete_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='UserName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
